on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:    
      name: Build
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Make
          run: make all
        
    

  
